### ISSUE TITLE
User relationship

### ISSUE THREAD

**Issue by jhosepharaujo** [jotaelesalinas/laravel-adminless-ldap-auth#47]
Hi @jotaelesalinas , i have a relationship between User and Profile. However, when I run dd ($ user-> profiles) in the athenticated method on the login controller, it returns an error saying that the method does not exist. I verified that the User class is of the type `JotaEleSalinas\AdminlessLdap\LdapUser`. How does the relationship work now?

**User.php**
```
class User extends Authenticatable
{
    use Notifiable;
...
	public function profiles()
		{
			return $this->HasMany(Profile::class);
		}
}
```
**LoginController.php**
```
class LoginController extends Controller
{
...
	protected function authenticated(Request $request, $user)
	{
			dd($user->profiles());
	}
}
```

**Error**

```
Error
Call to undefined method JotaEleSalinas\AdminlessLdap\LdapUser::profiles()
```

Have a nice day!!!

**Comment by jotaelesalinas** [comment]
Hi @jhosepharaujo . Because `JotaEleSalinas\AdminlessLdap\LdapUser` is not an Eloquent model (the data does not come from the database), it does not support relationships. You can either hardcode the user id in the related tables (losing the Eloquent "magic") or update `LoginController`  to synchronize your local `User` with the authenticated `LdapUser`. The latest could cause some issues when a user is removed from the LDAP server but still exists in your local database. Tread carefully.
